package io.seekflux.platform.agentruntime.domain.service.recovery;

public enum RecoveryPoint {
    BEFORE_PRE_TURN_CHECKPOINT,
    AFTER_PRE_TURN_CHECKPOINT,
    AFTER_MODEL_DECISION_COMMIT,
    AFTER_TOOL_EXECUTING_COMMIT,
    AFTER_SIDE_EFFECT_PREPARED,
    AFTER_SIDE_EFFECT_EXECUTING,
    AFTER_MUTATING_TOOL_RETURN_BEFORE_LEDGER_RESULT,
    AFTER_SIDE_EFFECT_RESULT_COMMIT,
    AFTER_TOOL_RESULT_COMMIT,
    BEFORE_POST_TURN_CHECKPOINT,
    AFTER_POST_TURN_CHECKPOINT,
    BEFORE_TERMINAL_CHECKPOINT,
    AFTER_TERMINAL_CHECKPOINT
}
