bind 127.0.0.1
port 6379
protected-mode yes
daemonize yes
dir /root/workwpace/SeekFlux/.local/redis/data
pidfile /root/workwpace/SeekFlux/.local/redis/run/redis.pid
logfile /root/workwpace/SeekFlux/.local/redis/logs/redis.log
appendonly yes
appenddirname appendonlydir
maxmemory-policy allkeys-lru

